-- Add new columns to products table
ALTER TABLE products
ADD COLUMN IF NOT EXISTS category VARCHAR(100) DEFAULT 'T-Shirt',
ADD COLUMN IF NOT EXISTS description TEXT,
ADD COLUMN IF NOT EXISTS sizes TEXT[] DEFAULT ARRAY['S', 'M', 'L', 'XL'],
ADD COLUMN IF NOT EXISTS colors TEXT[] DEFAULT ARRAY['Black', 'White'],
ADD COLUMN IF NOT EXISTS rating DECIMAL(2,1) DEFAULT 4.5,
ADD COLUMN IF NOT EXISTS is_new BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS images TEXT[]; 